name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        run: sudo apt-get install -y libjack-jackd2-dev

      - name: Configure
        run: ./autogen.sh

      - name: Build
        run: make dist
